import Head from "next/head";
import Navbar from "../components/Navbar";
import Results from "../components/Results";
import axios from "axios";
import { useEffect } from "react";
export default function Home({ results }) {
    console.log(results);
    useEffect(() => {
        localStorage.setItem("video", JSON.stringify(results));
    });
    return (
        <div>
            <Head>
                <title>ClipMist | Homepage</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* Navbar */}
            <Navbar />
            <hr className="w-full text-gray-600" />
            <div className="mt-4 flex items-start justify-end">
                {/* <Videos /> */}
                <Results result={results} />
            </div>
        </div>
    );
}
export const getServerSideProps = async (context) => {
    console.log("getserversideprops");
    return axios.get("http://localhost:3005/backend/home").then((res) => {
        return {
            props: {
                results: res.data,
            },
        };
    });
};
